### ISSUE TITLE
[docs] add contributors in every util docs to give everyone credit ⚡️

### ISSUE THREAD

**Issue by eneajaho** [nartc/ngxtension-platform#112]
This will help even when there are issues open, and we can easily assign contributors

**Comment by JeevanMahesha** [comment]
hi @eneajaho  I'm interested in take this take, before I start I need to know much more details on this task. correct me if I'm wrong we need to add the .all-contributorsrc page link in call the pages under the util docs?

**Comment by JeevanMahesha** [comment]
@nartc / @eneajaho  While exploring for this task, I came across @tomalaforge Angular challenges repository. In that repository's content section, he added the configuration where we can provide the author in the astrojs config.ts file. Here is the [link](https://github.com/tomalaforge/angular-challenges/blob/main/docs/src/content/config.ts) to that file . Please take a look at it and let me know if we can use this approach. Otherwise, if you have any other suggestions, please share them and I will work on it.

**Comment by tomalaforge** [comment]
@eneajaho Do you want to continue on this issue ? We can do something like Angular Challenges
<img width="764" alt="image" src="https://github.com/nartc/ngxtension-platform/assets/30832608/249a9975-3645-4270-826b-2fa2544aece5">

instead of Created by: we can add the contributor
and instead of challenge #1, we can add stable, unstable (see https://github.com/nartc/ngxtension-platform/issues/138)

What do you think ? I can implement it

**Comment by ajitzero** [comment]
Hi, I just looked at the PRs for this (#170 & #173) and wanted to know if we had considered using Astro's [Content Collections](https://docs.astro.build/en/guides/content-collections/) for this? And if it was dismissed, was there any reason other than simplicity or customization issues with Starlight?

Use-case: My first instinct on seeing the contributor name was to click it, so I figured there would be a structure for storing author metadata, e.g., a link to a personal website/blog, Twitter/X, etc. This can also be extended later to include badges like "GDE" or something (just an example).

**Comment by tomalaforge** [comment]
Yes I agree with you. I wanted to add a link but I decided It can be done on a second iteration. 
We can simply add an object contributor with the name and the prefer link (twitter, github, ...)

**Comment by ajitzero** [comment]
Yes, that would work too, for simplicity. I prefer using collections for the benefit of zod and the potential to reuse the collection elsewhere, like getting a count of utilities contributed by someone.

**Comment by tomalaforge** [comment]
Very good idea. It's done 👍
