### ISSUE TITLE
Add support function for router NavigationEnd event

### ISSUE THREAD

**Issue by va-stefanek** [nartc/ngxtension-platform#43]
Let's add an util function for catching whenever router navigation NavigationEnd event occur

e.g

```
export const routerNavigationEnd = () => {
  const router = inject(Router);

  return router.events.pipe(
    filter((event): event is NavigationEnd => event instanceof NavigationEnd)
  );
};
```

I am eager to add it if you would be interested with that one.

**Comment by eneajaho** [comment]
Hello @va-stefanek 

Can you give some usecases please? They will be valuable when creating the docs for the util.

**Comment by va-stefanek** [comment]
> Hello @va-stefanek
> 
> Can you give some usecases please? They will be valuable when creating the docs for the util.

We found it valuable because we had multiple instances where we needed to react to the end of navigation, such as hiding banners, changing page titles, and more. We had multiple router injections and the same filter across the entire app.

**Comment by nartc** [comment]
@va-stefanek this makes sense. Do you have any proposal API of what the helper(s) should look like?

**Comment by va-stefanek** [comment]
Honestly I am not sure, was thinking about something like that

```
import { Observable } from 'rxjs';
import { filter } from 'rxjs/operators';
import { NavigationEnd, Router, Event } from '@angular/router';

/**
 * Creates an Observable that emits when a navigation ends.
 * @returns An Observable of NavigationEnd events.
 */
export function routerNavigationEnd(): Observable<NavigationEnd> {
  const router = inject(Router);

  return router.events.pipe(
    filter((event: Event): event is NavigationEnd => event instanceof NavigationEnd)
  );
}
```

Additionaly like in some other helpers in the repo we can check whether it's in injection context and allow to pass 	`injector?: Injector` as parameter

**Comment by tomer953** [comment]
I have a very common use-case in my projects - 
When a user is being redirect to the /error route (ie “Something went wrong, please reload the page and try again”) (lets say the server went down, then after the navigation to the /error page it went back up)
We need to detect refresh event”in order to navigate him back to the root of the app.

 ```ts
 this.router.events
    .pipe(filter((rs): rs is NavigationEnd => rs instanceof NavigationEnd))
    .subscribe(event => {
      if (
        event.id === 1 &&
        event.url === event.urlAfterRedirects
      ) {
          // the user made page refresh - do your logic here (ie navigate to root page to try again)
      }
    })
```

**Comment by eneajaho** [comment]
@nartc I like this! I think a PR would be welcome @tomer953 @va-stefanek (also having the optional injector just in case) 🙌

**Comment by va-stefanek** [comment]
Ok so I will open an PR @eneajaho

**Comment by tomer953** [comment]
@nartc  There's a small inconsistency regarding the filenames and operator names. the filename is `navigation-end`, while the operator name is `injectNavigationEnd`. This is inconsistent with `inject-destroy`, where the filename and the operator name are the same.

This naming discrepancy also causes an issue in the Astro docs sidebar. The two inject operators are separated due to the sidebar being autogenerated based on **filenames**.

**Comment by va-stefanek** [comment]
@tomer953 I have been following [resize](https://github.com/nartc/ngxtension-platform/blob/main/libs/ngxtension/resize/src/resize.ts). I agree that might be good to agreed some consistency in naming of files and utils.
